server:
  port: 8082
  
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: books
        uri: lb://book-ws
        predicates:
        - Path=/books/*
        - Method=GET,POST,PUT,DELETE
      - id: employees
        uri: lb://employee-ws
        predicates:
        - Path=/employees/*
        - Method=GET,POST,PUT,DELETE
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    