server:
  port: 8082
  
spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/lms
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456789
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-ui
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: books
        uri: lb://book-ws
        predicates:
        - Path=/books/*
        - Method=GET,POST,PUT,DELETE
        filters:
        - AuthenticationFilter
      - id: employees
        uri: lb://employee-ws
        predicates:
        - Path=/employees/*
        - Method=GET,POST,PUT,DELETE
        filters:
        - AuthenticationFilter
      - id: members
        uri: lb://member-ws
        predicates:
        - Path=/member/*
        - Method=GET,POST,PUT,DELETE
        filters:
        - AuthenticationFilter
      - id: borrow-book
        uri: lb://borrow-book-ws
        predicates:
        - Path=/book/*
        - Method=GET,POST,PUT,DELETE
        filters:
        - AuthenticationFilter
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
jwt: 
  secret: ASrfUjiKlkGyfSeCgNMoMpKoHfCFzxDaweSrhIjytYfJHGHFDjFjawRdYfjyffyGuhiHhfFdserFYGijGftDetJooJJYftbvXzxzEwawGuiKkooJnbVCrxezxCCYhiOkjBbyvTfdlkjgyutdtyhfdewtaFDYGVHTDYTRFCUHgOIHjhfdxfeaszDC
  header: Authorization  
  validity: 20
  authDisabled: true
 
