server:
  port: 0
  
spring:
  application:
    name: exception-ws
  devtools:
    restart:
      enabled: true
      
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
